site_name: HEP manual
theme:
  features:
    - navigation.indexes

  name: null
  custom_dir: mkdocs-material/material
  
  palette:
    scheme: youtube

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: sv
  font:
    text: Gilroy ExtraBold
    code: Gilroy 
  favicon: assets/logoRed.svg
  
  logo: assets/ICO_01.svg
    
extra_css:
  - overrides/stylesheets/extra.css

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  

 
copyright: Copyright &copy 2022 Hep-online

extra:
  generator: false
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/hep-online/
      name: HEP on LinkedIn
      
mkdocs gh-deploy --force

